# Generated by Django 5.1.4 on 2025-04-29 22:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخطة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الشهري')),
                ('duration_days', models.IntegerField(help_text='عدد أيام سريان الاشتراك', verbose_name='المدة بالأيام')),
                ('max_trips', models.IntegerField(blank=True, help_text='إذا كان غير محدد، عدد الرحلات غير محدود', null=True, verbose_name='الحد الأقصى للرحلات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'خطة اشتراك',
                'verbose_name_plural': 'خطط الاشتراك',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_group', models.BooleanField(default=False, verbose_name='محادثة جماعية')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان المحادثة')),
                ('participants', models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='المشاركون')),
            ],
            options={
                'verbose_name': 'محادثة',
                'verbose_name_plural': 'المحادثات',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='معرف الجهاز')),
                ('status', models.BooleanField(default=True, verbose_name='الحالة')),
                ('status_del', models.BooleanField(default=False, verbose_name='محذوف')),
                ('city', models.CharField(max_length=50, verbose_name='المدينة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='CasheItemDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('from_location', models.CharField(max_length=255, verbose_name='من')),
                ('to_location', models.CharField(max_length=255, verbose_name='إلى')),
                ('item_description', models.TextField(verbose_name='وصف الشحنة')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الوزن (كجم)')),
                ('urgent', models.BooleanField(default=False, verbose_name='عاجل')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبول'), ('in_progress', 'قيد التوصيل'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashe_deliveries', to='apis.client', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طلب توصيل مسبق',
                'verbose_name_plural': 'طلبات التوصيل المسبقة',
            },
        ),
        migrations.CreateModel(
            name='CasheBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField()),
                ('passengers', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='يجب حجز مقعد واحد على الأقل'), django.core.validators.MaxValueValidator(20, message='الحد الأقصى 20 مقعد للحجز الواحد')])),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('failed', 'فشل'), ('cancelled', 'ملغى')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashe_bookings', to='apis.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('license_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الرخصة')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='التقييم')),
                ('total_trips', models.IntegerField(default=0, verbose_name='إجمالي الرحلات')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح للرحلات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سائق',
                'verbose_name_plural': 'السائقون',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='', verbose_name='مرفق')),
                ('is_read', models.BooleanField(default=False, verbose_name='تم القراءة')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='apis.chat', verbose_name='المحادثة')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='المحتوى')),
                ('is_read', models.BooleanField(default=False, verbose_name='تم القراءة')),
                ('notification_type', models.CharField(choices=[('booking', 'حجز'), ('trip', 'رحلة'), ('payment', 'دفع'), ('system', 'نظام')], default='system', max_length=50, verbose_name='نوع الإشعار')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرّف الكائن المرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('remaining_trips', models.IntegerField(blank=True, null=True, verbose_name='الرحلات المتبقية')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='apis.driver', verbose_name='السائق')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.subscriptionplan', verbose_name='الخطة')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد المتابعة'), ('resolved', 'تم الحل'), ('closed', 'مغلق')], default='open', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='apis.driver', verbose_name='مُعيّن إلى')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تذكرة دعم',
                'verbose_name_plural': 'تذاكر الدعم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField()),
                ('available_seats', models.PositiveIntegerField()),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('cancelled', 'ملغية'), ('full', 'مكتملة المقاعد')], default='pending', max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.driver')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='تعليق')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='apis.driver', verbose_name='السائق')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.client', verbose_name='المقيّم')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='apis.trip', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
            },
        ),
        migrations.CreateModel(
            name='ItemDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('receiver_name', models.CharField(max_length=255, verbose_name='اسم المستلم')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='هاتف المستلم')),
                ('item_description', models.TextField(verbose_name='وصف الشحنة')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الوزن (كجم)')),
                ('insurance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مبلغ التأمين')),
                ('delivery_code', models.CharField(max_length=10, verbose_name='كود الشحنة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_transit', 'قيد النقل'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='apis.trip', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'شحنة',
                'verbose_name_plural': 'الشحنات',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('passengers', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغى')], default='confirmed', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.client')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='apis.trip')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='الموقع')),
                ('order', models.PositiveIntegerField(verbose_name='ترتيب المحطة')),
                ('arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الوصول المتوقع')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='apis.trip', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'محطة توقف',
                'verbose_name_plural': 'محطات التوقف',
                'db_table': 'trip_stops',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('model', models.CharField(max_length=100, verbose_name='الموديل')),
                ('plate_number', models.CharField(max_length=50, unique=True, verbose_name='رقم اللوحة')),
                ('color', models.CharField(max_length=30, verbose_name='اللون')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='السعة')),
                ('vehicle_type', models.CharField(choices=[('sedan', 'سيدان'), ('suv', 'SUV'), ('van', 'فان'), ('truck', 'شاحنة')], default='sedan', max_length=20, verbose_name='نوع المركبة')),
                ('manufacture_year', models.IntegerField(blank=True, null=True, verbose_name='سنة الصنع')),
                ('inspection_expiry', models.DateField(blank=True, null=True, verbose_name='انتهاء الفحص الفني')),
                ('status', models.BooleanField(default=True, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'مركبة',
                'verbose_name_plural': 'المركبات',
                'db_table': 'vehicles',
                'indexes': [models.Index(fields=['vehicle_type'], name='vehicles_vehicle_d54349_idx'), models.Index(fields=['plate_number'], name='vehicles_plate_n_de64b1_idx')],
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicles',
            field=models.ManyToManyField(related_name='drivers', to='apis.vehicle', verbose_name='المركبات'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='الرصيد')),
                ('currency', models.CharField(choices=[('YE', 'ريال يمني')], default='YE', max_length=3, verbose_name='العملة')),
                ('is_locked', models.BooleanField(default=False, help_text='يمنع إجراء المعاملات إذا كانت المحفظة محظورة', verbose_name='محظورة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'محفظة',
                'verbose_name_plural': 'المحافظ',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('cancelled', 'ملغى'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('transfer_code', models.CharField(max_length=10, verbose_name='رمز التحويل')),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to='apis.wallet', verbose_name='محفظة المرسل')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='apis.wallet', verbose_name='محفظة المستقبل')),
            ],
            options={
                'verbose_name': 'تحويل مالي',
                'verbose_name_plural': 'التحويلات المالية',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('transaction_type', models.CharField(choices=[('charge', 'شحن'), ('transfer', 'تحويل'), ('withdraw', 'سحب'), ('payment', 'دفع'), ('refund', 'استرداد')], max_length=10, verbose_name='نوع العملية')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('cancelled', 'ملغى'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم المرجع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='apis.wallet', verbose_name='المحفظة')),
            ],
            options={
                'verbose_name': 'عملية',
                'verbose_name_plural': 'العمليات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('reason', models.CharField(choices=[('referral', 'مكافأة إحالة'), ('promotion', 'عرض ترويجي'), ('other', 'أخرى')], default='other', max_length=255, verbose_name='السبب')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مكافأة',
                'verbose_name_plural': 'المكافآت',
                'indexes': [models.Index(fields=['expiration_date'], name='apis_bonus_expirat_440be0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['city'], name='clients_city_c00b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='clients_status_98ee60_idx'),
        ),
        migrations.AddIndex(
            model_name='casheitemdelivery',
            index=models.Index(fields=['urgent'], name='apis_cashei_urgent_6b709c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='apis_messag_is_read_0b8fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='apis_notifi_is_read_a3fac3_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='apis_notifi_notific_ea6a82_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['end_date'], name='apis_subscr_end_dat_877d32_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['is_active'], name='apis_subscr_is_acti_fc1abd_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status'], name='apis_suppor_status_ed031d_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['priority'], name='apis_suppor_priorit_0abcd1_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rating'], name='apis_rating_rating_e3b123_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('trip', 'rated_by')},
        ),
        migrations.AddIndex(
            model_name='itemdelivery',
            index=models.Index(fields=['delivery_code'], name='apis_itemde_deliver_84d245_idx'),
        ),
        migrations.AddIndex(
            model_name='itemdelivery',
            index=models.Index(fields=['status'], name='apis_itemde_status_369bca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tripstop',
            unique_together={('trip', 'order')},
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['rating'], name='apis_driver_rating_b68803_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_available'], name='apis_driver_is_avai_faafb8_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['transfer_code'], name='apis_transf_transfe_e851bc_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status'], name='apis_transf_status_d34d41_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='apis_transa_transac_3fa0b8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='apis_transa_status_62daba_idx'),
        ),
    ]
