# Generated by Django 5.1.4 on 2025-01-18 19:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('data_type', models.CharField(max_length=100, verbose_name='نوع البيانات')),
                ('data', models.JSONField(verbose_name='البيانات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'بيانات نموذج الذكاء الاصطناعي',
                'verbose_name_plural': 'بيانات نماذج الذكاء الاصطناعي',
            },
        ),
        migrations.CreateModel(
            name='CasheBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('where_from', models.CharField(max_length=60, verbose_name='من أين')),
                ('to_where', models.CharField(max_length=60, verbose_name='إلى أين')),
                ('number_set', models.IntegerField(verbose_name='عدد الأشخاص')),
                ('at_time', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'حجز نقدي',
                'verbose_name_plural': 'الحجوزات النقدية',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخطة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('price', models.FloatField(verbose_name='السعر')),
                ('duration', models.IntegerField(verbose_name='المدة (بالأيام)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'خطة اشتراك',
                'verbose_name_plural': 'خطط الاشتراك',
                'db_table': 'subscription_plans',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('model', models.CharField(max_length=100, verbose_name='الموديل')),
                ('plate_number', models.CharField(max_length=50, unique=True, verbose_name='رقم اللوحة')),
                ('color', models.CharField(max_length=30, verbose_name='اللون')),
                ('capacity', models.IntegerField(verbose_name='السعة')),
                ('status', models.BooleanField(default=True, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'مركبة',
                'verbose_name_plural': 'المركبات',
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('driver', 'سائق'), ('customer', 'عميل')], max_length=10, verbose_name='نوع المستخدم')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف')),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group', verbose_name='المجموعات')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission', verbose_name='صلاحيات المستخدم')),
            ],
            options={
                'verbose_name': 'مستخدم مخصص',
                'verbose_name_plural': 'المستخدمون المخصصون',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('photo', models.TextField(blank=True, null=True, verbose_name='رابط الصورة')),
                ('device_id', models.TextField(blank=True, null=True, verbose_name='معرف الجهاز')),
                ('status', models.BooleanField(default=True, verbose_name='الحالة')),
                ('status_del', models.BooleanField(default=False, verbose_name='الحالة (محذوف)')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='المدينة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='apis.customuser', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('participants', models.ManyToManyField(related_name='chats', to='apis.customuser', verbose_name='المشاركون')),
            ],
            options={
                'verbose_name': 'محادثة',
                'verbose_name_plural': 'المحادثات',
            },
        ),
        migrations.CreateModel(
            name='CasheItemDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('pickup_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='موقع الاستلام')),
                ('dropoff_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='موقع التسليم')),
                ('item_description', models.TextField(verbose_name='وصف العنصر')),
                ('weight', models.FloatField(verbose_name='الوزن (كجم)')),
                ('at_time', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashe_received_items', to='apis.customuser', verbose_name='المستلم')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashe_sent_items', to='apis.customuser', verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'تسليم نقدي',
                'verbose_name_plural': 'التسليمات النقدية',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('amount', models.FloatField(verbose_name='المبلغ')),
                ('status', models.BooleanField(default=True, verbose_name='الحالة')),
                ('status_del', models.BooleanField(default=False, verbose_name='الحالة (محذوف)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.customuser', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مكافأة',
                'verbose_name_plural': 'المكافآت',
                'db_table': 'bonuses',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('license_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الرخصة')),
                ('status', models.BooleanField(default=True, verbose_name='الحالة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='apis.customuser', verbose_name='المستخدم')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis.vehicle', verbose_name='المركبة')),
            ],
            options={
                'verbose_name': 'سائق',
                'verbose_name_plural': 'السائقون',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='apis.chat', verbose_name='المحادثة')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='apis.customuser', verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('recommended_item_id', models.IntegerField(verbose_name='معرف العنصر الموصى به')),
                ('recommended_item_type', models.CharField(max_length=50, verbose_name='نوع العنصر الموصى به')),
                ('recommendation_score', models.FloatField(verbose_name='درجة التوصية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='apis.customuser', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'توصية',
                'verbose_name_plural': 'التوصيات',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.driver', verbose_name='المستخدم')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.subscriptionplan', verbose_name='الخطة')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد التنفيذ'), ('resolved', 'محلول')], default='open', max_length=20, verbose_name='الحالة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.customuser', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تذكرة دعم',
                'verbose_name_plural': 'تذاكر الدعم',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('start_location', models.CharField(max_length=100, verbose_name='نقطة الانطلاق')),
                ('end_location', models.CharField(max_length=100, verbose_name='وجهة الوصول')),
                ('departure_time', models.DateTimeField(verbose_name='وقت المغادرة')),
                ('available_seats', models.IntegerField(verbose_name='عدد المقاعد المتاحة')),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر المقعد')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='حالة الرحلة')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.driver', verbose_name='السائق')),
            ],
            options={
                'verbose_name': 'رحلة',
                'verbose_name_plural': 'الرحلات',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('rating', models.IntegerField(verbose_name='التقييم (1 إلى 5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='التعليق')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.driver', verbose_name='السائق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.customuser', verbose_name='المستخدم')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.trip', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
            },
        ),
        migrations.CreateModel(
            name='ItemDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('pickup_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='موقع الاستلام')),
                ('dropoff_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='موقع التسليم')),
                ('item_description', models.TextField(verbose_name='وصف العنصر')),
                ('weight', models.FloatField(verbose_name='الوزن (كجم)')),
                ('insurance', models.BooleanField(default=False, verbose_name='التأمين')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_transit', 'قيد النقل'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_items', to='apis.customuser', verbose_name='المستلم')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_items', to='apis.customuser', verbose_name='المرسل')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.trip', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'تسليم عنصر',
                'verbose_name_plural': 'تسليم العناصر',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('seat_number', models.IntegerField(verbose_name='عدد المقاعد')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحجز')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='حالة الحجز')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.client', verbose_name='العميل')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.trip', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('location', models.CharField(max_length=255, verbose_name='الموقع')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='apis.trip', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'توقف الرحلة',
                'verbose_name_plural': 'توقفات الرحلات',
                'db_table': 'trip_stops',
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('activity_type', models.CharField(max_length=50, verbose_name='نوع النشاط')),
                ('activity_data', models.JSONField(verbose_name='بيانات النشاط')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.customuser', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل النشاط',
                'verbose_name_plural': 'سجلات النشاط',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('preferences_data', models.JSONField(verbose_name='بيانات التفضيلات')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='apis.customuser', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تفضيلات المستخدم',
                'verbose_name_plural': 'تفضيلات المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='رصيد المحفظة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='apis.customuser', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'محفظة',
                'verbose_name_plural': 'المحافظ',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='حالة العملية')),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='apis.wallet', verbose_name='محفظة المرسل')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='apis.wallet', verbose_name='محفظة المستلم')),
            ],
            options={
                'verbose_name': 'حوالة',
                'verbose_name_plural': 'الحوالات',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('transaction_type', models.CharField(choices=[('charge', 'شحن'), ('transfer', 'تحويل'), ('withdraw', 'سحب'), ('payment', 'دفع')], max_length=10, verbose_name='نوع العملية')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='حالة العملية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='apis.wallet', verbose_name='المحفظة')),
            ],
            options={
                'verbose_name': 'عملية',
                'verbose_name_plural': 'العمليات',
            },
        ),
        migrations.CreateModel(
            name='ChargeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('card_code', models.CharField(max_length=20, unique=True, verbose_name='رمز الشحن')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قيمة الشحن')),
                ('is_used', models.BooleanField(default=False, verbose_name='هل تم الاستخدام؟')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_cards', to='apis.wallet', verbose_name='المحفظة')),
            ],
            options={
                'verbose_name': 'كارت شحن',
                'verbose_name_plural': 'كروت الشحن',
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='apis_trip_status_e536e0_idx'),
        ),
    ]
