# Generated by Django 5.1.4 on 2025-01-07 23:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasheBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wherefram', models.CharField(max_length=60, verbose_name='من وين')),
                ('towhere', models.CharField(max_length=60, verbose_name='على وين')),
                ('numberset', models.IntegerField(verbose_name='انت ومن : العدد')),
                ('at_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخطة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('price', models.FloatField(verbose_name='السعر')),
                ('duration', models.IntegerField(verbose_name='المدة (بالأيام)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'خطة اشتراك',
                'verbose_name_plural': 'خطط الاشتراك',
                'db_table': 'subscription_plans',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('model', models.CharField(max_length=100, verbose_name='الموديل')),
                ('plate_number', models.CharField(max_length=50, unique=True, verbose_name='رقم اللوحة')),
                ('color', models.CharField(max_length=30, verbose_name='اللون')),
                ('capacity', models.IntegerField(verbose_name='السعة')),
                ('status', models.BooleanField(default=True, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'مركبة',
                'verbose_name_plural': 'المركبات',
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('driver', 'Driver'), ('customer', 'Customer')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('photo', models.TextField(null=True, verbose_name='رابط الصورة')),
                ('device_id', models.TextField(null=True, verbose_name='معرف الجهاز')),
                ('status', models.BooleanField(default=True, verbose_name='الحالة')),
                ('status_del', models.BooleanField(default=True, verbose_name='الحالة (محذوف)')),
                ('city', models.CharField(max_length=50, null=True, verbose_name=' المدينة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis.customuser')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='CasheItemDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=100, null=True, verbose_name='المرسل')),
                ('pickup_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='موقع الاستلام')),
                ('dropoff_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='موقع التسليم')),
                ('item_description', models.TextField(verbose_name='وصف العنصر')),
                ('weight', models.FloatField(verbose_name='الوزن بالكيلوجرام')),
                ('at_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.customuser', verbose_name='المستلم')),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.FloatField(null=True, verbose_name='المبلغ')),
                ('status', models.BooleanField(default=True, verbose_name='الحالة')),
                ('status_del', models.BooleanField(default=True, verbose_name='الحالة (محذوف)')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.customuser', verbose_name='معرف المستخدم')),
            ],
            options={
                'verbose_name': 'مكافأة',
                'verbose_name_plural': 'المكافآت',
                'db_table': 'bonuses',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('license_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الرخصة')),
                ('status', models.BooleanField(default=True, verbose_name='الحالة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis.customuser')),
                ('vehicl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis.vehicle', verbose_name='المركبة')),
            ],
            options={
                'verbose_name': 'سائق',
                'verbose_name_plural': 'السائقون',
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.driver', verbose_name='العميل')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.subscriptionplan', verbose_name='خطة الاشتراك')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد التنفيذ'), ('resolved', 'محلولة')], default='open', max_length=20, verbose_name='الحالة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.customuser', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'تذكرة دعم',
                'verbose_name_plural': 'تذاكر الدعم',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('start_location', models.CharField(max_length=100, verbose_name='نقطة الانطلاق')),
                ('end_location', models.CharField(max_length=100, verbose_name='وجهة الوصول')),
                ('departure_time', models.DateTimeField(verbose_name='وقت المغادرة')),
                ('available_seats', models.IntegerField(verbose_name='عدد المقاعد المتاحة')),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر المقعد')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='حالة الرحلة')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.driver', verbose_name='السائق')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('rating', models.IntegerField(verbose_name='التقييم (1 إلى 5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='التعليق')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.driver', verbose_name='السائق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.customuser', verbose_name='العميل')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.trip', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
            },
        ),
        migrations.CreateModel(
            name='ItemDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sender', models.CharField(max_length=100, verbose_name='المرسل')),
                ('pickup_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='موقع الاستلام')),
                ('dropoff_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='موقع التسليم')),
                ('item_description', models.TextField(verbose_name='وصف العنصر')),
                ('weight', models.FloatField(verbose_name='الوزن بالكيلوجرام')),
                ('insurance', models.BooleanField(default=False, verbose_name='قابل للكسر/ضمان')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_transit', 'قيد النقل'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.customuser', verbose_name='المستلم')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.trip', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'تسليم عنصر',
                'verbose_name_plural': 'تسليم العناصر',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(verbose_name=' عدد المقاعد ')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحجز')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.client', verbose_name='العميل')),
                ('trip', models.ForeignKey(default='mohamme', on_delete=django.db.models.deletion.CASCADE, to='apis.trip', verbose_name='الرحلة')),
            ],
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('location', models.CharField(max_length=255, verbose_name=' الموقع الحالي')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.trip', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': ' الرحلة وين',
                'verbose_name_plural': 'تتبع الرحلات',
                'db_table': 'stops',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='رصيد المحفظة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis.customuser', verbose_name='المحفظة الخاصة ب')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('from_wallet', models.CharField(max_length=100, verbose_name='محفظة المرسل')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='حالة العملية')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('transaction_type', models.CharField(choices=[('charge', 'Charge'), ('transfer', 'Transfer'), ('withdraw', 'Withdraw'), ('payment', 'Payment')], max_length=10, verbose_name='نوع العملية')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='حالة العملية')),
                ('description', models.TextField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChargeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('card_code', models.CharField(max_length=20, unique=True, verbose_name=' رمز الشحن')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name=' قيمة الشحن')),
                ('is_used', models.BooleanField(default=False)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='apis_trip_status_e536e0_idx'),
        ),
    ]
