# Generated by Django 5.1.4 on 2025-04-29 22:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'حجز', 'verbose_name_plural': 'الحجوزات'},
        ),
        migrations.AlterModelOptions(
            name='cashebooking',
            options={'verbose_name': 'حجز مسبق', 'verbose_name_plural': 'الحجوزات المسبقة'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-departure_time'], 'verbose_name': 'رحلة', 'verbose_name_plural': 'الرحلات'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='passengers',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cashebooking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cashebooking',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.JSONField(default=list, help_text='قائمة بأرقام/أسماء المقاعد المحددة', verbose_name='المقاعد المحجوزة'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='المبلغ الإجمالي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashebooking',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية'),
        ),
        migrations.AddField(
            model_name='trip',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='estimated_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='المدة المتوقعة'),
        ),
        migrations.AddField(
            model_name='trip',
            name='route_coordinates',
            field=models.TextField(blank=True, help_text='تنسيق JSON لإحداثيات المسار (خط الطول والعرض)', null=True, verbose_name='إحداثيات المسار'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='apis.client', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='apis.trip', verbose_name='الرحلة'),
        ),
        migrations.AlterField(
            model_name='cashebooking',
            name='departure_time',
            field=models.DateTimeField(verbose_name='وقت المغادرة'),
        ),
        migrations.AlterField(
            model_name='cashebooking',
            name='from_location',
            field=models.CharField(max_length=255, verbose_name='من'),
        ),
        migrations.AlterField(
            model_name='cashebooking',
            name='passengers',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الركاب'),
        ),
        migrations.AlterField(
            model_name='cashebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبول'), ('failed', 'فشل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='cashebooking',
            name='to_location',
            field=models.CharField(max_length=255, verbose_name='إلى'),
        ),
        migrations.AlterField(
            model_name='cashebooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashe_bookings', to='apis.client', verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='available_seats',
            field=models.IntegerField(default=0, verbose_name='عدد المقاعد المتاحة'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.DateTimeField(verbose_name='وقت المغادرة'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='apis.driver', verbose_name='السائق'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='from_location',
            field=models.CharField(max_length=255, verbose_name='من'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price_per_seat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر لكل مقعد'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('cancelled', 'ملغية')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_location',
            field=models.CharField(max_length=255, verbose_name='إلى'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='apis_bookin_status_c52b97_idx'),
        ),
        migrations.AddIndex(
            model_name='cashebooking',
            index=models.Index(fields=['departure_time'], name='apis_casheb_departu_485e03_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['departure_time'], name='apis_trip_departu_6dd7bf_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='apis_trip_status_e536e0_idx'),
        ),
    ]
