# Generated by Django 5.1.4 on 2025-05-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='رمز التحويل'),
        ),
        migrations.DeleteModel(
            name='RetryQueue',
        ),
    ]
