# Generated by Django 5.1.4 on 2025-02-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cashebooking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cashebooking',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tripstop',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tripstop',
            name='updated_at',
        ),
    ]
