# Generated by Django 5.1.4 on 2025-02-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='available_seats',
            field=models.IntegerField(verbose_name='عدد المقاعد المتاحة'),
        ),
    ]
