# Generated by Django 5.1.4 on 2025-05-07 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcmtoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'FCM Token', 'verbose_name_plural': 'FCM Tokens'},
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='device_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Device Information'),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='token',
            field=models.CharField(max_length=255, unique=True, verbose_name='FCM Token'),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='fcmtoken',
            index=models.Index(fields=['created_at'], name='apis_fcmtok_created_c30c97_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmtoken',
            index=models.Index(fields=['user'], name='apis_fcmtok_user_id_5a13fa_idx'),
        ),
    ]
