# Generated by Django 5.1.4 on 2025-01-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='cashebooking',
            options={'verbose_name': 'طلب رحلة ', 'verbose_name_plural': ' طلبات الرحلات'},
        ),
        migrations.AlterModelOptions(
            name='casheitemdelivery',
            options={'verbose_name': 'طلب ارسال ', 'verbose_name_plural': 'طلبات الارسال '},
        ),
        migrations.AlterModelOptions(
            name='itemdelivery',
            options={'verbose_name': 'ارسال الاغرض', 'verbose_name_plural': 'الاغراض المرسة معا الرحلات'},
        ),
        migrations.DeleteModel(
            name='ChargeCard',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.DeleteModel(
            name='UserActivityLog',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
