# Generated by Django 5.1.4 on 2025-05-23 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='apis.vehicle', verbose_name='المركبة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المسافة (كم)'),
        ),
    ]
