# Generated by Django 5.1.4 on 2025-02-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_trip_available_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='available_seats',
            field=models.IntegerField(default=0, verbose_name='عدد المقاعد المتاحة'),
        ),
    ]
