# Generated by Django 5.1.4 on 2025-05-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_booking_options_alter_cashebooking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='where_location',
            field=models.CharField(default=1, max_length=255, verbose_name='وين'),
            preserve_default=False,
        ),
    ]
