# Generated by Django 5.1.4 on 2025-04-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_driver_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
