# Generated by Django 5.1.4 on 2025-01-08 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_driver_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'verbose_name': 'حوالة', 'verbose_name_plural': 'الحوالات'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'محفظة', 'verbose_name_plural': 'المحفظة'},
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='apis.customuser'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='from_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_wallet', to='apis.wallet', verbose_name='محفظة المرسل'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_wallet', to='apis.wallet', verbose_name='محفظة المستلم'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='apis.customuser', verbose_name='المحفظة الخاصة ب'),
        ),
    ]
