# Generated by Django 5.1.4 on 2025-05-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_transfer_transfer_code_delete_retryqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='معالجة'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='محظورة'),
        ),
    ]
