# Generated by Django 5.1.4 on 2025-02-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_trip_available_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='price_per_seat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر لكل مقعد'),
        ),
    ]
