# Generated by Django 5.1.4 on 2025-04-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_trip_distance_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبول'), ('failed', 'فشل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
