# Generated by Django 5.1.4 on 2025-01-08 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_transfer_options_alter_wallet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casheitemdelivery',
            name='reciver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver_cach', to='apis.customuser', verbose_name='المستلم'),
        ),
        migrations.AlterField(
            model_name='casheitemdelivery',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_cach', to='apis.customuser', verbose_name='المرسل'),
        ),
        migrations.AlterField(
            model_name='itemdelivery',
            name='reciver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver_item', to='apis.customuser', verbose_name='المستلم'),
        ),
        migrations.AlterField(
            model_name='itemdelivery',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_item', to='apis.customuser', verbose_name='المرسل'),
        ),
    ]
