# Generated by Django 5.1.4 on 2025-04-22 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_notification_options_remove_notification_body_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'verbose_name': 'مكافأة', 'verbose_name_plural': 'المكافآت'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price'], 'verbose_name': 'خطة اشتراك', 'verbose_name_plural': 'خطط الاشتراك'},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(default=1, verbose_name='الوصف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_trips',
            field=models.IntegerField(blank=True, help_text='إذا كان غير محدد، عدد الرحلات غير محدود', null=True, verbose_name='الحد الأقصى للرحلات'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='reason',
            field=models.CharField(choices=[('referral', 'مكافأة إحالة'), ('promotion', 'عرض ترويجي'), ('other', 'أخرى')], default='other', max_length=255, verbose_name='السبب'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.IntegerField(help_text='عدد أيام سريان الاشتراك', verbose_name='المدة بالأيام'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الخطة'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الشهري'),
        ),
        migrations.AddIndex(
            model_name='bonus',
            index=models.Index(fields=['expiration_date'], name='apis_bonus_expirat_440be0_idx'),
        ),
    ]
