# Generated by Django 5.1.4 on 2025-04-22 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_bonus_options_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='auto_renew',
        ),
        migrations.AddField(
            model_name='subscription',
            name='remaining_trips',
            field=models.IntegerField(blank=True, null=True, verbose_name='الرحلات المتبقية'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='apis.driver', verbose_name='السائق'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.subscriptionplan', verbose_name='الخطة'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ البدء'),
        ),
    ]
