# Generated by Django 5.1.4 on 2025-01-13 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_casheitemdelivery_reciver_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripstop',
            options={'verbose_name': 'الرحلة وين', 'verbose_name_plural': 'تتبع الرحلات'},
        ),
        migrations.RenameField(
            model_name='cashebooking',
            old_name='towhere',
            new_name='to_where',
        ),
        migrations.RenameField(
            model_name='cashebooking',
            old_name='wherefram',
            new_name='where_from',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='vehicl',
            new_name='vehicle',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='cashebooking',
            name='numberset',
        ),
        migrations.RemoveField(
            model_name='casheitemdelivery',
            name='reciver',
        ),
        migrations.RemoveField(
            model_name='itemdelivery',
            name='reciver',
        ),
        migrations.AddField(
            model_name='bonus',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.customuser', verbose_name='معرف المستخدم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cashebooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cashebooking',
            name='number_set',
            field=models.IntegerField(default=1, verbose_name='انت ومن: العدد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashebooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='casheitemdelivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='casheitemdelivery',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cashe_received_items', to='apis.customuser', verbose_name='المستلم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casheitemdelivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='itemdelivery',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_items', to='apis.customuser', verbose_name='المستلم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bonus',
            name='status_del',
            field=models.BooleanField(default=False, verbose_name='الحالة (محذوف)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.IntegerField(verbose_name='عدد المقاعد'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.trip', verbose_name='الرحلة'),
        ),
        migrations.AlterField(
            model_name='casheitemdelivery',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashe_sent_items', to='apis.customuser', verbose_name='المرسل'),
        ),
        migrations.AlterField(
            model_name='chargecard',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قيمة الشحن'),
        ),
        migrations.AlterField(
            model_name='chargecard',
            name='card_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='رمز الشحن'),
        ),
        migrations.AlterField(
            model_name='chargecard',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='هل تم استخدام الكارت؟'),
        ),
        migrations.AlterField(
            model_name='chargecard',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_cards', to='apis.wallet'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status_del',
            field=models.BooleanField(default=False, verbose_name='الحالة (محذوف)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='apis.customuser'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='apis.customuser'),
        ),
        migrations.AlterField(
            model_name='itemdelivery',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_items', to='apis.customuser', verbose_name='المرسل'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='apis.wallet'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='from_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='apis.wallet', verbose_name='محفظة المرسل'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='apis.wallet', verbose_name='محفظة المستلم'),
        ),
        migrations.AlterField(
            model_name='tripstop',
            name='location',
            field=models.CharField(max_length=255, verbose_name='الموقع الحالي'),
        ),
        migrations.AlterField(
            model_name='tripstop',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='apis.trip', verbose_name='الرحلة'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='apis.customuser', verbose_name='المحفظة الخاصة ب'),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('recommended_items', models.JSONField(verbose_name='العناصر الموصى بها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.customuser', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'توصية',
                'verbose_name_plural': 'توصيات',
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('activity_type', models.CharField(max_length=50, verbose_name='نوع النشاط')),
                ('activity_data', models.JSONField(verbose_name='بيانات النشاط')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الطابع الزمني')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.customuser', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل النشاط',
                'verbose_name_plural': 'سجلات النشاط',
            },
        ),
    ]
