from django.contrib import admin
from .models import *

admin.site.register(CustomUser)
admin.site.register(Client)
admin.site.register(Wallet)
admin.site.register(ChargeCard)
admin.site.register(Transaction)
admin.site.register(Transfer)
admin.site.register(Vehicle)
admin.site.register(Driver)
admin.site.register(Bonus)
admin.site.register(Trip)
admin.site.register(TripStop)
admin.site.register(Rating)
admin.site.register(Support)
admin.site.register(SubscriptionPlan)
admin.site.register(Subscription)
admin.site.register(Booking)
admin.site.register(CasheBooking)
admin.site.register(ItemDelivery)
admin.site.register(CasheItemDelivery)
admin.site.register(UserActivityLog)
admin.site.register(Recommendation)
