# Generated by Django 5.1.4 on 2025-02-02 23:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('capacity', models.IntegerField(default=4)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='نقطة الانطلاق')),
                ('to_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='نقطة الوصول')),
                ('departure_time', models.DateTimeField(verbose_name='وقت المغادرة المطلوب')),
                ('passengers', models.IntegerField(default=1, verbose_name='عدد الركاب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('merged', 'تم الدمج'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='Ai.client')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='من')),
                ('to_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='إلى')),
                ('departure_time', models.DateTimeField(verbose_name='وقت المغادرة')),
                ('available_seats', models.IntegerField(default=0, verbose_name='عدد المقاعد المتاحة')),
                ('price_per_seat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر لكل مقعد')),
                ('route_data', models.JSONField(blank=True, null=True, verbose_name='بيانات المسار')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='Ai.driver')),
            ],
            options={
                'ordering': ['-departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.JSONField(default=list, help_text='قائمة بأرقام المقاعد', verbose_name='المقاعد المحجوزة')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('status', models.CharField(choices=[('confirmed', 'مؤكد'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='confirmed', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Ai.client')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Ai.trip')),
            ],
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['departure_time'], name='Ai_trip_departu_e9464c_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='Ai_trip_status_de961c_idx'),
        ),
    ]
