# Generated by Django 5.1.4 on 2025-02-03 22:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'مؤكد'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='departure_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='from_location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='passengers',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('merged', 'تم الدمج'), ('failed', 'فشل')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='to_location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='trip',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='from_location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price_per_seat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغاة')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
