# Generated by Django 5.1.4 on 2025-02-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ai', '0002_alter_booking_seats_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='to_location',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='from_lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='from_lng',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='to_lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='to_lng',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='current_lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='current_lng',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='from_lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='from_lng',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='to_lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='to_lng',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
