# Generated by Django 5.1.4 on 2025-02-03 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ai', '0003_remove_bookingrequest_from_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='route_data',
        ),
    ]
